import 'package:health_mate/features/cycle/domain/entities/cycle_phase.dart';
import 'package:health_mate/features/cycle/domain/entities/workout_template.dart';

/// 03_WORKOUT_MATRIX.json matrix 를 Dart const list 로 옮긴 것.
/// MVP fallback 모드: 영상 없음 / illustrated 포맷 / moves 배열 표시 + 타이머.
///
/// id 포맷: '{workout_type}__{phase_id}'.
/// skip(권장 안 함) 항목은 별도로 [skipMatrix] 에 보관.
const List<WorkoutTemplate> kWorkoutMatrix = [
  // ── stretching_yoga ──────────────────────────────────────────────
  WorkoutTemplate(
    id: 'stretching_yoga__menstrual',
    phase: CyclePhase.menstrual,
    workoutType: 'stretching_yoga',
    workoutTypeKorean: '스트레칭 / 요가',
    priority: WorkoutPriority.core,
    durationSeconds: 300,
    titleSuggestion: '월경기 따뜻한 5분 요가',
    descriptionForUser: '복부와 허리 통증 완화에 도움되는 부드러운 동작',
    productionPriority: 1,
    moves: ["Child's Pose", 'Cat-Cow', 'Supine Twist', 'Legs-up-the-Wall'],
  ),
  WorkoutTemplate(
    id: 'stretching_yoga__follicular',
    phase: CyclePhase.follicular,
    workoutType: 'stretching_yoga',
    workoutTypeKorean: '스트레칭 / 요가',
    priority: WorkoutPriority.warmup,
    durationSeconds: 240,
    titleSuggestion: '난포기 활기찬 워밍업 스트레칭',
    descriptionForUser: '본격 운동 전 가볍게 몸 깨우기',
    productionPriority: 2,
    moves: ['Sun Salutation A', 'Dynamic Lunge', 'Arm Circles'],
  ),
  WorkoutTemplate(
    id: 'stretching_yoga__ovulatory',
    phase: CyclePhase.ovulatory,
    workoutType: 'stretching_yoga',
    workoutTypeKorean: '스트레칭 / 요가',
    priority: WorkoutPriority.cooldown,
    durationSeconds: 240,
    titleSuggestion: '배란기 운동 후 쿨다운',
    descriptionForUser: '고강도 운동 후 회복 스트레칭',
    productionPriority: 3,
    moves: ['Forward Fold', 'Pigeon Pose', 'Supine Hamstring Stretch'],
  ),
  WorkoutTemplate(
    id: 'stretching_yoga__luteal',
    phase: CyclePhase.luteal,
    workoutType: 'stretching_yoga',
    workoutTypeKorean: '스트레칭 / 요가',
    priority: WorkoutPriority.core,
    durationSeconds: 300,
    titleSuggestion: '황체기 차분한 5분 요가',
    descriptionForUser: 'PMS 완화와 마음 진정에 좋은 동작',
    productionPriority: 1,
    moves: [
      'Reclined Butterfly',
      'Seated Forward Fold',
      'Spinal Twist',
      'Savasana',
    ],
  ),
  // ── light_cardio ─────────────────────────────────────────────────
  WorkoutTemplate(
    id: 'light_cardio__menstrual',
    phase: CyclePhase.menstrual,
    workoutType: 'light_cardio',
    workoutTypeKorean: '가벼운 카디오 (산책 가이드)',
    priority: WorkoutPriority.soft,
    durationSeconds: 300,
    titleSuggestion: '월경기 천천히 걷기 5분',
    descriptionForUser: '느린 페이스의 가이드 산책. 통증 완화에 도움',
    productionPriority: 3,
    moves: ['1분 천천히', '2분 호흡 맞추기', '3분 자연스러운 페이스', '4분 깊게 호흡', '5분 마무리'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'light_cardio__follicular',
    phase: CyclePhase.follicular,
    workoutType: 'light_cardio',
    workoutTypeKorean: '가벼운 카디오 (산책 가이드)',
    priority: WorkoutPriority.main,
    durationSeconds: 300,
    titleSuggestion: '난포기 빠르게 걷기 5분',
    descriptionForUser: '심박수를 살짝 올리는 활기찬 워킹',
    productionPriority: 1,
    moves: ['빠른 페이스 워밍업 1분', '본 페이스 3분', '쿨다운 1분'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'light_cardio__ovulatory',
    phase: CyclePhase.ovulatory,
    workoutType: 'light_cardio',
    workoutTypeKorean: '가벼운 카디오 (산책 가이드)',
    priority: WorkoutPriority.soft,
    durationSeconds: 300,
    titleSuggestion: '배란기 회복 산책',
    descriptionForUser: '고강도 운동 사이 회복일에',
    productionPriority: 4,
    moves: ['편한 페이스로 5분'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'light_cardio__luteal',
    phase: CyclePhase.luteal,
    workoutType: 'light_cardio',
    workoutTypeKorean: '가벼운 카디오 (산책 가이드)',
    priority: WorkoutPriority.main,
    durationSeconds: 300,
    titleSuggestion: '황체기 마음 진정 산책',
    descriptionForUser: '기분 안정에 좋은 자연 속 걷기 가이드',
    productionPriority: 2,
    moves: ['깊은 호흡 1분', '풍경 보며 걷기 3분', '천천히 마무리 1분'],
    format: WorkoutFormat.audioGuide,
  ),
  // ── strength_training ────────────────────────────────────────────
  WorkoutTemplate(
    id: 'strength_training__follicular',
    phase: CyclePhase.follicular,
    workoutType: 'strength_training',
    workoutTypeKorean: '근력 운동 (밴드/체중)',
    priority: WorkoutPriority.main,
    durationSeconds: 300,
    titleSuggestion: '난포기 5분 근력 빌드업',
    descriptionForUser: '이 시기에 근육이 가장 잘 성장합니다',
    productionPriority: 1,
    moves: ['Squat', 'Glute Bridge', 'Push-up Modified', 'Plank'],
  ),
  WorkoutTemplate(
    id: 'strength_training__ovulatory',
    phase: CyclePhase.ovulatory,
    workoutType: 'strength_training',
    workoutTypeKorean: '근력 운동 (밴드/체중)',
    priority: WorkoutPriority.main,
    durationSeconds: 300,
    titleSuggestion: '배란기 강한 근력 5분',
    descriptionForUser: '최고 컨디션, 한계까지 도전',
    productionPriority: 1,
    moves: ['Jump Squat', 'Tricep Dip', 'Push-up', 'Side Plank'],
  ),
  WorkoutTemplate(
    id: 'strength_training__luteal',
    phase: CyclePhase.luteal,
    workoutType: 'strength_training',
    workoutTypeKorean: '근력 운동 (밴드/체중)',
    priority: WorkoutPriority.soft,
    durationSeconds: 300,
    titleSuggestion: '황체기 가벼운 근력 유지',
    descriptionForUser: '강도 낮춰서 페이스 유지',
    productionPriority: 2,
    moves: ['Wall Sit', 'Bird Dog', 'Modified Plank'],
  ),
  // ── hiit ─────────────────────────────────────────────────────────
  WorkoutTemplate(
    id: 'hiit__follicular',
    phase: CyclePhase.follicular,
    workoutType: 'hiit',
    workoutTypeKorean: '고강도 인터벌 (HIIT)',
    priority: WorkoutPriority.intro,
    durationSeconds: 300,
    titleSuggestion: '난포기 HIIT 입문 5분',
    descriptionForUser: '20초 운동 + 10초 휴식 × 8라운드',
    productionPriority: 3,
    moves: ['Mountain Climber', 'High Knees', 'Squat Jump', 'Burpee Modified'],
  ),
  WorkoutTemplate(
    id: 'hiit__ovulatory',
    phase: CyclePhase.ovulatory,
    workoutType: 'hiit',
    workoutTypeKorean: '고강도 인터벌 (HIIT)',
    priority: WorkoutPriority.main,
    durationSeconds: 300,
    titleSuggestion: '배란기 풀 HIIT 5분',
    descriptionForUser: '타바타: 20초 ON / 10초 OFF',
    productionPriority: 1,
    moves: ['Burpee', 'Jump Squat', 'Plank to Push-up', 'Tuck Jump'],
  ),
  // ── breathing_meditation ─────────────────────────────────────────
  WorkoutTemplate(
    id: 'breathing_meditation__menstrual',
    phase: CyclePhase.menstrual,
    workoutType: 'breathing_meditation',
    workoutTypeKorean: '호흡 / 명상',
    priority: WorkoutPriority.core,
    durationSeconds: 180,
    titleSuggestion: '월경기 통증 완화 호흡 3분',
    descriptionForUser: '4-7-8 호흡법으로 신경계 진정',
    productionPriority: 2,
    moves: ['들숨 4초', '참기 7초', '날숨 8초', '× 8회 반복'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'breathing_meditation__follicular',
    phase: CyclePhase.follicular,
    workoutType: 'breathing_meditation',
    workoutTypeKorean: '호흡 / 명상',
    priority: WorkoutPriority.short,
    durationSeconds: 120,
    titleSuggestion: '하루를 여는 2분 호흡',
    descriptionForUser: '에너지 깨우는 빠른 호흡',
    productionPriority: 4,
    moves: ['빠른 들숨 2초', '날숨 2초', '× 30회'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'breathing_meditation__ovulatory',
    phase: CyclePhase.ovulatory,
    workoutType: 'breathing_meditation',
    workoutTypeKorean: '호흡 / 명상',
    priority: WorkoutPriority.short,
    durationSeconds: 120,
    titleSuggestion: '운동 전 집중 2분',
    descriptionForUser: '고강도 운동 전 정신 준비',
    productionPriority: 4,
    moves: ['들숨 4초', '날숨 4초', '× 15회'],
    format: WorkoutFormat.audioGuide,
  ),
  WorkoutTemplate(
    id: 'breathing_meditation__luteal',
    phase: CyclePhase.luteal,
    workoutType: 'breathing_meditation',
    workoutTypeKorean: '호흡 / 명상',
    priority: WorkoutPriority.core,
    durationSeconds: 180,
    titleSuggestion: '황체기 PMS 진정 호흡 3분',
    descriptionForUser: '감정 기복 완화에 좋은 깊은 호흡',
    productionPriority: 2,
    moves: ['들숨 5초', '참기 2초', '날숨 7초', '× 12회'],
    format: WorkoutFormat.audioGuide,
  ),
];

/// 03_WORKOUT_MATRIX.json 의 priority="skip" 조합. 추천 후보에서 제외.
/// (workoutType, phase) → 권장 안 함 사유.
const Map<String, String> kSkipMatrix = {
  'strength_training__menstrual': '월경기 근력 운동은 통증 가능성. 추천 안 함.',
  'hiit__menstrual': '월경기 고강도는 신체 부담. 추천 안 함.',
  'hiit__luteal': '황체기는 회복기. HIIT 권장 안 함.',
};

/// 특정 phase 의 추천 후보만 필터링 (skip 제외).
Iterable<WorkoutTemplate> workoutsForPhase(CyclePhase phase) {
  return kWorkoutMatrix.where((w) => w.phase == phase);
}
